name: docker image build and push to hub
on:
 [workflow_dispatch]
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup and build image
        run: docker build ./ -t chidhu0001/bookapp-ngrx:latest
      - name: push the docker image to hub
        run: |
          docker login -u chidhu0001 -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push chidhu0001/bookapp-ngrx:latest